### ISSUE TITLE
creates error in exist because return statement is empty

### ISSUE THREAD

**Issue by arokis** [arokis/bdnprint_if#13]
https://github.com/arokis/bdnprint_if/blob/0ba4a38dbb148dd6a705e54846d5f78942d24e86/modules/intermediate_format/markerset.xqm#L108

Diese Abfrage erzeugt einen Fehler in eXist, da markerset:marker keine leere sequence, sondern ein element zurückgeben muss. Ich verstehe den Zweck hinter der Abfrage auch nicht ganz: Wir möchten alle öffnenden  Marker, die Varianten sind und in einem, rdg gestetzt werden ausschließen? Warum nicht auch die schließenden?

Wenn du die v-marker[@context='rdg'] nicht haben möchtest, dann sollten wir die an einer anderen Stelle rausnehmen, denn die markerset:marker function ist eigentlich nur als Markerconstructor gedacht, quasi als Blaupause eines Markers ;-)

**Comment by MRodz** [comment]
Ich habe sie rausgenommen, weil sie unnötig sind und insbesondere das öffnende Element zu Fehlern in der späteren Serialisierung führt. Habe eine neue Version als Pullrequest gestellt, in der die Abfrage außerhalb des Konstruktors gestellt wird -- auch wenn mir nicht ganz klar ist, warum das Element überhaupt erstellt werden sollte, wenn es nicht gebraucht wird...
