### ISSUE TITLE
Fehlender open-Marker

### ISSUE THREAD

**Issue by MRodz** [arokis/bdnprint_if#16]
Bei der folgenden Auszeichnung im Nösselt:

`<app><lem><seg type="item"><app><lem/><rdg wit="#c" type="pt"><milestone unit="p" edRef="#c" type="structure"/><seg xml:id="var_1_51_p3_1">Unter den Neueren:</seg></rdg></app><milestone unit="line" edRef="#c" type="structure"/><seg xml:id="var_1_51_p3_item1"><index indexName="persons"><term>Mosheim, Johann Lorenz von</term></index><persName ref="#textgrid:250j4"><hi>Joh. Lorenz von</hi><app><lem><hi>Mosheims</hi></lem><rdg wit="#c" type="v"><hi>Mosheim</hi></rdg></app></persName> kurze Anweisung, die Gottesgelahrtheit vernünftig zu erlernen – – zum Druck befördert von <index indexName="persons"><term>Windheim, Christian Ernst von</term></index><hi><persName ref="#textgrid:250j5">Christian Ernst von Windheim</persName></hi>, Helmstädt 1756.<ptr target="#textgrid:250j7"/> in <choice><abbr>gr.</abbr><expan>groß</expan></choice> 8.</seg></seg></lem><rdg wit="#a" type="om"/></app>`

wird zwar das schließende om von `<rdg wit="#a" type="om"/>` (am Schluss) erzeugt, das öffenende jedoch nicht. Das öffnende müsste gleich nach seg[@type = 'item'], denke ich (die Auszeichnung ist so verschachtelt, dass es schwer zu sagen ist).

**Comment by MRodz** [comment]
Ähnlicher Fall hier mit fehlendem open-Marker: 

`<app><lem><note place="end" type="authorial" xml:id="noe_2_1_186_note1" n="1"><app><lem/><rdg wit="#c" type="pt"><choice><abbr><hi>Anm.</hi></abbr><expan>Anmerkung</expan></choice></rdg>...</note></lem><rdg wit="#a" type="om"/></app>`

Sieht so aus, als träte das Problem dann auf, wenn das erste Element im lem mit Text ein Apparat mit leerem lem und rdg[@type = 'pt'] ist.

**Comment by arokis** [comment]
Jup, kann ich bestätigen!
Dieser Fall ist bisher nicht deklariert. Wo soll ich in diesen Fällen den Marker setzen?

**Comment by MRodz** [comment]
Läuft. Danke!
