### ISSUE TITLE
bdn_string.xqm vs. string.xqm

### ISSUE THREAD

**Issue by MRodz** [arokis/bdnprint_if#3]
Das Modul heißt string.xqm, wird aber überall, inkl. bei der namespace-Deklaration, als "bdn_string.xqm" referenziert.

**Comment by arokis** [comment]
Habe ich korrigiert. Verweis geht nun auf "string.xqm". Issue kann m.E. geschlossen werden.

**Comment by MRodz** [comment]
Stimmt, alles top. :)
