### ISSUE TITLE
rdgMarker an falscher Stelle

### ISSUE THREAD

**Issue by MRodz** [arokis/bdnprint_if#5]
Folgende Auszeichnung:

`<lem>
<app><lem>...</lem><rdg type="pp">1</rdg></app></lem><rdg type="pp">2</rdg>`

führt zu einem rdgMarker[@context = 'lem'] im rdg mit Inhalt 1.
Stelle im Griesbach: "gewißen, zumal ältern und nur die theologischen Systeme". Es geht um das rdg "gewissen".

**Comment by MRodz** [comment]
Es kommt auch vor, wenn das zweite rdg[@type = 'ppl'] ist. Findet sich verstreut immer wieder im Griesbach.

**Comment by MRodz** [comment]
Ich hab mir das noch mal angeschaut. Es kommt in folgenden Fällen (ich gehe hier von BdN/TEI aus) zu Problem (keine abgeschlossene Aufzählung):

1. 2x rdg[@type = 'pp']
    `<app>
        <lem>... 
            <app>
                <lem>...</lem>
                <rdg @type = 'pp'>...</rdg>
            </app>
        </lem>
        <rdg @type = 'pp'>Some Text</rdg>
    </app>`

2. rdg[@type = 'v'] in rdg[@type = 'om']
        `<app>
            <lem>... 
                <app>
                   <lem>...</lem>
                   <rdg @type = 'v'>...</rdg>
                </app>
            </lem>
            <rdg @type = 'om'>Some Text</rdg>
        </app>`

TBC

Sorry für die blöde Darstellung, das Markdown geht bei XML irgendwie nicht richtig. :(

**Comment by MRodz** [comment]
` <app>
                                    <lem>beigelegt werden können;</lem>
                                    <rdg wit="#a" type="pp">beigeleget werden,</rdg>
                                </app></lem>
                            <rdg wit="#d" type="pp">Theil nehmen und wahrhaft göttliche Werke verrichten
                                kann;</rdg>
                        </app> `

**Comment by arokis** [comment]
Die Marker sollten nun an der richtigen Stelle stehen

**Comment by MRodz** [comment]
Im Fall @type = 'v' + @type = 'om' ja, wenn das zweite rdg[@type = 'pp'] ist, kommt es noch zu einem Problem: Der rdgMarker müsste hinter dem inneren app (oder dem äußeren lem, das ist egal)stehen, damit er nach dem Einschubzeichen abgebildet wird. Ich hab das mal in einem Beispiel markiert (@@ zeigt an, wo es hinsoll, und %%, wo es gerade steht):

`<app><lem>bloß <app><lem>gewißen, zumal ältern und nur die theologischen Systeme betreffenden%%</lem><rdg wit="#b" type="pp">gewissen</rdg></app>@@</lem><rdg wit="#a" type="pp">blos gewissen</rdg></app> Streitigkeiten,`

Es geht hier um den Marker von a. Da bei rdg[@type = 'pp'] das Einschubzeichen || gesetzt wird, kommt es zum Phänomen 

gewißen, zumal ältern und nur die theologischen Systeme betreffendenb\ **a**\ ||b1 ||a2

statt

gewißen, zumal ältern und nur die theologischen Systeme betreffendenb\ ||b1 **a**\ ||a2

**Comment by arokis** [comment]
Danke für die Rückmeldung. Ich habe eine neue Regel für letzte tei:rdg[@type="pp" or @type="pt"] für die right-branch-axis definiert. Jetzt setzt er für diese Fälle einen Marker hinter dem parent:tei:app.

**Comment by MRodz** [comment]
Sieht gut aus, vielen Dank!
