### ISSUE TITLE
Whitespaces bei pb

### ISSUE THREAD

**Issue by MRodz** [arokis/bdnprint_if#9]
Bei der Verarbeitung von pb sollten die Leerzeichen vorher und nachher, wenn vorhanden, behalten werden. Gibt es keine, werden auch keine gesetzt.

Ich weiß nicht genau, ob es nicht vielleicht am <hi> liegt, aber z.B.

`<hi>Studium der popu</hi><pb edRef="#d" n="4"/><hi>lären`

wird zu 

`<hi>Studium der popu</hi>
    <pb edRef="#d" n="4"/>
<hi>lären Dogmatik</hi>`

und damit zu _Studium der popu_ | _lären Dogmatik_ in TeX.
Ähnlich auch `<item><pb edRef="#b" type="sp" n="XIII"/>`, das im Zwischenformat vor dem pb ein Leerzeichen hat.

**Comment by arokis** [comment]
Die Auszeichnung <hi>Studium der popu</hi><pb edRef="#d" n="4"/><hi>lären [...]</hi> ist zum Ersten quatsch! So wäre es richtig: <hi>Studium der popu<pb edRef="#d" n="4"/>lären [...]</hi>.

Das hier allerdings zwei Leerzeichen produziert werden ist ein Problem. Das liegt daran, dass xQuery die beiden hi und den pb in jeweils eine Zeile setzt. Vlt. kriegen wir das mit dem output serialize-parameter raus. zumindest gebe ich jedem pb, ein @break="no", wenn direkt davor und danach kein Leerzeichen kommt.

**Comment by MRodz** [comment]
Alles klar, ich guck mal, dass ich die Flag gut verwende. Die Auszeichnung kommt übrigens daher, dass der pb nicht kursiv gesetzt werden soll. Das wird im Nösselt auch zuhauf gemacht.

**Comment by arokis** [comment]
Ich kann dir hier auch andere Flags setzen ... so wie du es hier haben möchtest :-)
Ich habe mir den Grund für die Auszeichnung schon gedacht, aber lässt sich das Problem nicht anders (als in der Auszeichnung) lösen? So suggeriert die Auszeichnung zwei separate Kursivierungen anstelle einer durchlaufenden Kursivierung.

**Comment by MRodz** [comment]
Die Flags sind schon in Ordnung! Wichtig ist ja nur, dass ich ein Unterscheidungskriterium habe.

Wegen der Auszeichnung: Das müsstest du mit Münster klären. Natürlich kann ich den Code so umstellen, dass die pagebreaks nicht kursiviert werden.

**Comment by MRodz** [comment]
Ich habe gerade mal die PDF durchgeschaut und mir sind noch ein paar Fälle aufgefallen, bei denen ich dich bitten möchte, noch mal nachzujustieren:

@break = 'no' sollte nicht stehen (d.h. es wird ein Leerzeichen gesetzt) vor:
- docAuthor
- app (z.B. `<pb edRef="#d" type="sp" n="XV"/><app><lem>Inhalt.</lem>`. pb steht in einer eigenen Zeile, daher sollte ein Leerzeichen folgen)
- index (z.B. `<pb edRef="#a" n="4" break="no"/><index indexName="subjects">term>Deutlichkeit</term>`)
- seg (z.B.` <pb edRef="#a" n="36" break="no"/><seg xml:id="var_a_65_head">65.`)
- bibl (z.B. `<pb edRef="#a" n="108" break="no"/><bibl type="biblical-reference"><citedRange n="Gal:5:19 Gal:5:21">Gal. 5, 19. 21.`)

 Ansonsten sieht es aber schon sehr gut aus. Danke!

**Comment by arokis** [comment]
ich habe hier die Regel angepasst. @break="no" wird dann gesetzt, wenn tei:pb eine orthographisch e Einheit (sprich, zwischen zweit strings steht, wobei der erste kein Leerzeichen am Ende und der Zweite kein Leerzeichen am Anfang hat.) In den Fällen, die du oben listest, setzte ich nun ein Flag @break="yes" ... erstmal nur zur Kontrolle. Wenn uns das nicht hilft, kann ich es auch wieder rausnehmen.

**Comment by MRodz** [comment]
Dankeschön! 
Es trifft leider noch nicht alle Fälle, z.B. vor docAuthor. Ich denke, man bekommt alle Fälle am einfachsten, wenn man abfragt, ob der pb in einer eigenen Zeile steht. Wenn ja, dann break="yes", ansonsten break="no". Lässt sich das relativ einfach umsetzen oder sollte ich das einfacher bei mir lösen?

**Comment by MRodz** [comment]
Wie besprochen:

Bitte @break = 'yes' setzen, wenn pb[following::node()[1][matches(., '[\n]') and not(matches(substring(.,1,1), '[\w ]'))]]. Das matcht zwar ein wenig mehr, als notwendig ist, da TeX aber mehrere aufeinanderfolgende Leerzeichen zu einem zusammenfasst, sollte das kein Problem sein.

**Comment by arokis** [comment]
Gut. Ein tei:pb, das in einer eigenen Zeile steht, wird nun mit @break="yes" geflagt.
